---
format:
  html: 
    theme: morph
    fontsize: 1.1em
    linestretch: 1.7
    page-layout: full
    smooth-scroll: true
---

## Presentation

<p class="text-primary-emphasis">Master's student in Business Economics with a specialization in Data Science <br> I've always loved understanding why things are the way they are, which is what led me to this field. Through my models, it allows me to constantly gather more information.</p>

<table style="width: 100%; text-align: center;">
  <tr>
    <td style="padding: 10px;">
      <svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-envelope" fill="currentColor" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M0 4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V4zm2-1a1 1 0 0 0-1 1v.217l7 4.2 7-4.2V4a1 1 0 0 0-1-1H2zm13 2.383l-4.758 2.855L15 11.114v-5.73zm-.034 6.878L9.271 8.82 8 9.583 6.728 8.82l-5.694 3.44A1 1 0 0 0 2 13h12a1 1 0 0 0 .966-.739zM1 11.114l4.758-2.876L1 5.383v5.73z"/></svg>
      <a href="mailto:greg.jlt03@gmail.com" class="text-primary-emphasis">greg.jlt03@gmail.com</a>
    </td>
    <td style="padding: 10px;">
      <svg width="1.5em" height="1.5em" viewBox="0 0 24 24" class="mdi:linkedin" fill="currentColor" xmlns="http://www.w3.org/2000/svg"><path d="M19 3a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2zm-.5 15.5v-5.3a3.26 3.26 0 0 0-3.26-3.26c-.85 0-1.84.52-2.32 1.3v-1.11h-2.79v8.37h2.79v-4.93c0-.77.62-1.4 1.39-1.4a1.4 1.4 0 0 1 1.4 1.4v4.93zM6.88 8.56a1.68 1.68 0 0 0 1.68-1.68c0-.93-.75-1.69-1.68-1.69a1.69 1.69 0 0 0-1.69 1.69c0 .93.76 1.68 1.69 1.68m1.39 9.94v-8.37H5.5v8.37z"/></svg>
      <a href="https://www.linkedin.com/in/grégory-jaillet-b78476187" class="text-primary-emphasis">My LinkedIn</a>
    </td>
    <td style="padding: 10px;">
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"/></svg>
      <a href="https://github.com/Greg-jllt" class="text-primary-emphasis">My GitHub</a>
    </td>
  </tr>
</table>


::: {.panel-tabset}

## Education

<span class="text-primary-emphasis">**Faculté des deux Lions, Tours | Master's in Business Economics | Sept 2023 - Sept 2025**</span>

<div>
  <ul class="text-primary-emphasis">
    <li>Micro-econometric and micro-economic studies</li>
    <li>Learning and implementation of unsupervised classification systems (PCA, MCA, ...) and supervised methods using ensemble techniques (Boosting, Random Forest, ...) and deep learning (CNN, RNN, ...)</li>
  </ul>
</div>

<span class="text-primary-emphasis">**Faculté des deux Lions, Tours | Bachelor's in Economics | Sept 2021 - Sept 2023**</span>

<div>
  <ul class="text-primary-emphasis">
    <li>Micro-economic, statistical, mathematical, and econometric studies</li>
    <li>Discovery and learning of programming software</li>
  </ul>
</div>

<span class="text-primary-emphasis">**IUT de l'Indre, Cheatauroux | DUT in Business and Administration Management | Sept 2019 - Sept 2021**</span>

<div>
  <ul class="text-primary-emphasis">
    <li>Entry of accounting and inventory records</li>
    <li>Bank reconciliations</li>
    <li>Review of ledgers and preparation of financial statements</li>
  </ul>
</div>

## Experience

<h4 class="text-primary-emphasis">Internships</h4>

<ul class="text-primary-emphasis">
  <li>**Reworld Media | Data Scientist Intern | June - August 2024**</li>
  <ul>
    <li>Assisting in the implementation of an analysis process and machine learning workflow to optimally predict whether titles held by Reworld Media will be referenced on Google Discover</li>
  </ul>

  <li>**ADMR de l'indre | Accounting Assistant Intern | April - June 2021**</li>
  <ul>
    <li>Assisted with the completion of the 2020 financial statements</li>
    <li>Bank reconciliations</li>
    <li>Created a dashboard in Excel</li>
  </ul>
</ul>

<h4 class="text-primary-emphasis">Jobs</h4>

<ul class="text-primary-emphasis">
  <li>**Castorama | Garden Department Sales Associate | July 2023**</li>
  <ul>
    <li>Shelving merchandise</li>
    <li>Advising and directing customers</li>
  </ul>

  <li>**Ciblex | Warehouse Worker | July 2022**</li>
  <ul>
    <li>Sorting packages</li>
    <li>Preparation of orders</li>
    <li>Management of the warehouse</li>
  </ul>
</ul>

## Skills

- <h4 class="text-primary-emphasis">Hard skills</h4>

    - **R**
  <div class="progress">
    <div class="progress-bar progress-bar-striped" role="progressbar" style="width: 66%;" aria-valuenow="66" aria-valuemin="0" aria-valuemax="100"></div>
  </div>
  <div>
    <ul class="text-primary-emphasis">
      <li>Visualization with ggplot2</li>
      <li>Data manipulation with dplyr</li>
      <li>Report creation with Rmarkdown</li>
      <li>Machine Learning with the tidymodels framework</li>
    </ul>
  </div>

    - **Python**
  <div class="progress">
      <div class="progress-bar progress-bar-striped bg-success" role="progressbar" style="width: 66%;" aria-valuenow="66" aria-valuemin="0" aria-valuemax="100"></div>
  </div>
  <div>
    <ul class="text-primary-emphasis">
      <li>Visualization with Matplotlib and Altair</li>
      <li>User interface creation with Streamlit</li>
      <li>Machine Learning with Scikit-Learn</li>
      <li>Also familiar with: pandas, numpy, scipy, SQLAlchemy</li>
    </ul>
  </div>

    - **SQL**
  <div class="progress">
      <div class="progress-bar progress-bar-striped bg-warning" role="progressbar" style="width: 40%;" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100"></div>
  </div>
  <div>
    <ul class="text-primary-emphasis">
      <li>Table manipulation: aggregations, joins, pivots, ...</li>
    </ul>
  </div>

    - **VBA**
  <div class="progress">
    <div class="progress-bar progress-bar-striped bg-info" role="progressbar" style="width: 50%;" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>
  </div>
  <div>
    <ul class="text-primary-emphasis">
      <li>Basic Knowledge</li>
    </ul>
  </div>

    - **HTML/CSS**
  <div class="progress">
    <div class="progress-bar progress-bar-striped bg-danger" role="progressbar" style="width: 
    30%;" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100">
    </div>
  </div>

## Projects

  - **BatchMonitor** <br>
  <p class="text-primary-emphasis">BatchMonitor is a package that provides tools for linear optimization problems, specifically for bulk purchasing. It determines optimal lot combinations, solves dual problems for profit maximization, and analyzes price variation impacts. <br>
  Beside the function to solve primal and dual problem, the package also provides an lite interface, made with streamlit, to enter and visualize the results.</p>

  - **Churn Prediction for a Telecom Company**<br>
  <p class="text-primary-emphasis">This project aims to predict the churn of a iranian telecom company's customers. The data was on kaggle and contains information about the customers, their contracts, and their usage.<br> The project was divided into 3 parts: data exploration, model building, and model evaluation.</p>