project:
  type: website
  output-dir: docs

website:
  title: "Grégory"
  navbar:
    left:
      - href: Presentation.qmd
        text: Home
      - href: Education.qmd
        text: Education
      - href: Experience.qmd
        text: Experience
      - href: Skills.qmd
        text: Skills and Projects

format:
  html:
    theme: morph
    css: styles.css
    fontsize: 1.1em
    linestretch: 1.7
    page-layout: full
    smooth-scroll: true
